### ISSUE TITLE
Sound issue Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV)'

### ISSUE THREAD

**Issue by SHAW900** [x25today/voipwardialer#18]
hi everyone thank you for your support and help

i install all as per steps but i have a little problem at you can se its showing me error Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV)'

any guess where i went wrong:

(venv) root@DESKTOP-BR3HB9S:/home/user/sip_work/voipwardialer/dialer# python dialer.py call sip:test9@77.72.174.129 sip:77.72.174.129 test99*yj0 3***** +44******** V22 8n1
21:32:37.256         os_core_unix.c !pjlib 2.10-dev for POSIX initialized
21:32:37.259         sip_endpoint.c  .Creating endpoint instance...
21:32:37.260                  pjlib  .select() I/O Queue created (0x2bb7060)
21:32:37.260         sip_endpoint.c  .Module "mod-msg-print" registered
21:32:37.261        sip_transport.c  .Transport manager created.
21:32:37.262           pjsua_core.c  .PJSUA state changed: NULL --> CREATED
Adding modem

Registering sip:localhost
Registration completed (sip:localhost) status= 200 (OK)
Adding account

Registering sip:77.72.174.129
Registration completed (sip:77.72.174.129) status= 200 (OK)
Dialing +44******* with modem V22-8n1
Calling +44********2
Closing
Traceback (most recent call last):
  File "dialer.py", line 97, in <module>
    main()
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "dialer.py", line 92, in call
    current_call = dialer.dial(phone_number, modem_alias, phone_number)
  File "/home/user/sip_work/voipwardialer/dialer/src/dialer.py", line 132, in dial
    cb=self._get_callback(EndpointType.ACCOUNT, call_id=_call_id)
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/pjsua.py", line 1283, in make_call
    self._lib()._err_check("make_call()", self, err)
  File "/home/user/sip_work/venv/lib/python3.6/site-packages/pjsua.py", line 2722, in _err_check
    raise Error(op_name, obj, err_code, err_msg)
pjsua.Error: Object: {Account sip:t*y00@77.72.174.129}, **operation=make_call(), error=b'Unable to find default audio device (PJMEDIA_EAUD_NODEFDEV)'**
(venv) root@DESKTOP-BR3HB9S:/home/user/sip_work/voipwardialer/dialer#

**Comment by fpietrosanti** [comment]
Are you running it on a VPS without an audio device or on a Desktop computer?

Asking because the first testing and uses has been done on a computer with an audio device, so i'm wondering if it isn't needed to setup a virtual-dummy sound device?

**Comment by gdassori** [comment]
If is that the case, I'd look to 
https://stackoverflow.com/questions/16483635/pjsip-new-call-error-unable-to-find-default-audio-device-pjmedia-eaud-nodef
and 
modprobe snd-dummy enable=1 index=5 id="dummy"

**Comment by SHAW900** [comment]
Yes i download and install on VPS  can you please guide me virtual-dummy sound device setup ?
as i am not good in Linux.

thank you in advance.

**Comment by krishnastvSMSC** [comment]
Hi am also facing face issue , am using Mac OS X . How to resolve the issue.
